version: '3'

services:
  server:
    build: .
    command: sh -c "npm run build && npm run prod"
    environment:
      - NODE_ENV=production
      - ACCESS_TOKEN= ${ACCESS_TOKEN}
      - REFRESH_TOKEN= ${REFRESH_TOKEN}
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.9
  client:
    build: ../${BRANCH_NAME}_client/
    command: sh -c "npm run build"
    environment:
      - NODE_ENV=production
    volumes:
      - web-client-build:/client/build
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
volumes:
  web-client-build:
