name: Releases

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Check out code
        uses: actions/checkout@v2
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: false
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}